version: "3.7"
services:
  adminview:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEF_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DEF_PASSWORD}
    ports:
      - '80:80'
  dockerpg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: todo-db
    ports:
      - '${DOCKER_DB_PORT}:5432'
    volumes:
      - myvol:/var/lib/postgresql/data
  server:
    image: node-server
    depends_on:
      - dockerpg
    ports:
      - '3000:3000'
volumes:
  myvol: